// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38q_YjkpnzHWSb-xrtl7C9yefJSHHODU',
    appId: '1:537078166783:web:c9d32c11c2369dd82408ca',
    messagingSenderId: '537078166783',
    projectId: 'amour-1ff80',
    authDomain: 'amour-1ff80.firebaseapp.com',
    storageBucket: 'amour-1ff80.firebasestorage.app',
    measurementId: 'G-TMQECP6NSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcasJnj_pHdng6fiZC3c2TM1ApjfiseWY',
    appId: '1:537078166783:android:65d9c17ac390329d2408ca',
    messagingSenderId: '537078166783',
    projectId: 'amour-1ff80',
    storageBucket: 'amour-1ff80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7QJBVv06mWAft4C9JwQld3dBI-BrLeI',
    appId: '1:537078166783:ios:070f33226a5627842408ca',
    messagingSenderId: '537078166783',
    projectId: 'amour-1ff80',
    storageBucket: 'amour-1ff80.firebasestorage.app',
    iosBundleId: 'com.example.amour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7QJBVv06mWAft4C9JwQld3dBI-BrLeI',
    appId: '1:537078166783:ios:070f33226a5627842408ca',
    messagingSenderId: '537078166783',
    projectId: 'amour-1ff80',
    storageBucket: 'amour-1ff80.firebasestorage.app',
    iosBundleId: 'com.example.amour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38q_YjkpnzHWSb-xrtl7C9yefJSHHODU',
    appId: '1:537078166783:web:60d6e4c686adb7f92408ca',
    messagingSenderId: '537078166783',
    projectId: 'amour-1ff80',
    authDomain: 'amour-1ff80.firebaseapp.com',
    storageBucket: 'amour-1ff80.firebasestorage.app',
    measurementId: 'G-2LFWFJL9FQ',
  );
}
